apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
  labels:
    cattle.io/creator: norman
  annotations:
    field.cattle.io/projectId: ${RANCHER_PROJECT_ID}
    field.cattle.io/resourceQuota: '{"limit":{"requestsCpu":"4000m","requestsMemory":"8192Mi","limitsCpu":"16000m","limitsMemory":"32768Mi"}}'
    field.cattle.io/containerDefaultResourceLimit: '{"requestsCpu":"100m","requestsMemory":"128Mi","limitsCpu":"500m","limitsMemory":"512Mi"}'
